import {
    ArrowUpRight,
    Receipt,
    Wallet,
    ArrowDownLeft,
    ArrowRightLeft,
    PiggyBank,
    Percent,
    TrendingUp,
    TrendingDown,
    RotateCcw,
    CreditCard,
    FileText,
    Banknote,
    Home,
    Landmark,
    Smartphone,
    Shield,
    Coins,
    Car,
    BarChart3,
    Building2,
    Store,
    Zap,
    Briefcase,
    Users,
    HelpCircle,
} from "lucide-react-native";

import { TransactionKind, EntityType, AccountType } from "./enums";

export const TRANSACTION_ICON_MAP: Record<string, any> = {
    [TransactionKind.PAYMENT]: ArrowUpRight,
    [TransactionKind.BILL_PAYMENT]: Receipt,
    [TransactionKind.WITHDRAWAL]: Wallet,
    [TransactionKind.DEPOSIT]: ArrowDownLeft,
    [TransactionKind.TRANSFER]: ArrowRightLeft,
    [TransactionKind.INCOME]: PiggyBank,
    [TransactionKind.INTEREST]: Percent,
    [TransactionKind.DIVIDEND]: TrendingUp,
    [TransactionKind.REFUND]: RotateCcw,
    [TransactionKind.BUY]: TrendingDown,
    [TransactionKind.SELL]: TrendingUp,
    [TransactionKind.FEE]: CreditCard,
    [TransactionKind.ADJUSTMENT]: FileText,
    [TransactionKind.LOAN_PAYMENT]: Banknote,
    [TransactionKind.RENTAL_INCOME]: Home,
};

export const TRANSACTION_LABEL_MAP: Record<string, string> = {
    [TransactionKind.PAYMENT]: "Payment",
    [TransactionKind.BILL_PAYMENT]: "Bill Payment",
    [TransactionKind.WITHDRAWAL]: "Withdrawal",
    [TransactionKind.DEPOSIT]: "Deposit",
    [TransactionKind.TRANSFER]: "Transfer",
    [TransactionKind.INCOME]: "Income",
    [TransactionKind.INTEREST]: "Interest",
    [TransactionKind.DIVIDEND]: "Dividend",
    [TransactionKind.REFUND]: "Refund",
    [TransactionKind.BUY]: "Buy",
    [TransactionKind.SELL]: "Sell",
    [TransactionKind.FEE]: "Fee",
    [TransactionKind.ADJUSTMENT]: "Adjustment",
    [TransactionKind.LOAN_PAYMENT]: "Loan Payment",
    [TransactionKind.RENTAL_INCOME]: "Rental Income",
};

export const ASSET_ICON_MAP: Record<string, any> = {
    [AccountType.CHECKING]: Landmark,
    [AccountType.SAVINGS]: Landmark,
    [AccountType.CASH]: Wallet,
    [AccountType.CREDIT_CARD]: CreditCard,
    [AccountType.LOAN]: Banknote,
    [AccountType.BROKERAGE]: TrendingUp,
    [AccountType.INVESTMENT]: BarChart3,
    [AccountType.MOBILE_MONEY]: Smartphone,
    [AccountType.PENSION]: Shield,
    [AccountType.REAL_ESTATE]: Home,
    [AccountType.CRYPTO]: Coins,
    [AccountType.VEHICLE]: Car,
    [AccountType.OTHER]: HelpCircle,
};

export const ENTITY_ICON_MAP: Record<string, any> = {
    [EntityType.BANK]: Landmark,
    [EntityType.MNO]: Smartphone,
    [EntityType.PSP]: Building2,
    [EntityType.MICROFINANCE]: PiggyBank,
    [EntityType.BROKER]: Briefcase,
    [EntityType.GOVERNMENT]: Shield,
    [EntityType.MERCHANT]: Store,
    [EntityType.UTILITY_COMPANY]: Zap,
    [EntityType.EMPLOYER]: Building2,
    [EntityType.CREDIT_UNION]: Landmark,
    [EntityType.INSURANCE_COMPANY]: Shield,
    [EntityType.TAX_AUTHORITY]: Shield,
    [EntityType.PERSON]: Users,
    [EntityType.OTHER]: HelpCircle,
};
